-- Agent identities, tokens, OAuth and the MCP audit log (claude/rontext-network-hub),
-- follow-ups (claude/sleepy-noether), notes.author and drafts.follow_up_id.
--
-- Generated by `drizzle-kit generate` as the exact diff from main's schema, then
-- made idempotent (IF NOT EXISTS; constraints swallow duplicate_object), so the
-- build can apply it every time: see scripts/migrate-additive.ts.

CREATE TABLE IF NOT EXISTS "follow_up_scans" (
	"source" text NOT NULL,
	"thread_ref" text NOT NULL,
	"last_message_at" timestamp with time zone NOT NULL,
	"scanned_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "follow_up_scans_source_thread_ref_pk" PRIMARY KEY("source","thread_ref")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "follow_ups" (
	"id" serial PRIMARY KEY NOT NULL,
	"source" text NOT NULL,
	"thread_ref" text NOT NULL,
	"key" text NOT NULL,
	"contact_id" integer,
	"person_name" text NOT NULL,
	"person_email" text,
	"kind" text NOT NULL,
	"title" text NOT NULL,
	"detail" text,
	"due_on" date,
	"link" text,
	"last_message_at" timestamp with time zone NOT NULL,
	"status" text DEFAULT 'open' NOT NULL,
	"snoozed_until" timestamp with time zone,
	"closed_at" timestamp with time zone,
	"author" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mcp_agents" (
	"id" serial PRIMARY KEY NOT NULL,
	"key" text NOT NULL,
	"access" text DEFAULT 'read' NOT NULL,
	"tools" text[],
	"note" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "mcp_agents_key_unique" UNIQUE("key")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mcp_audit" (
	"id" serial PRIMARY KEY NOT NULL,
	"at" timestamp with time zone DEFAULT now() NOT NULL,
	"agent_key" text NOT NULL,
	"agent_id" integer,
	"via" text NOT NULL,
	"tool" text NOT NULL,
	"kind" text NOT NULL,
	"ok" boolean NOT NULL,
	"error" text,
	"args" jsonb,
	"duration_ms" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mcp_oauth_clients" (
	"client_id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"redirect_uris" text[] NOT NULL,
	"secret_hash" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mcp_oauth_codes" (
	"code_hash" text PRIMARY KEY NOT NULL,
	"client_id" text NOT NULL,
	"agent_id" integer NOT NULL,
	"redirect_uri" text NOT NULL,
	"code_challenge" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "mcp_tokens" (
	"id" serial PRIMARY KEY NOT NULL,
	"agent_id" integer NOT NULL,
	"kind" text NOT NULL,
	"token_hash" text NOT NULL,
	"hint" text NOT NULL,
	"client_id" text,
	"expires_at" timestamp with time zone,
	"last_used_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"revoked_at" timestamp with time zone,
	CONSTRAINT "mcp_tokens_token_hash_unique" UNIQUE("token_hash")
);
--> statement-breakpoint
ALTER TABLE "drafts" ADD COLUMN IF NOT EXISTS "follow_up_id" integer;
--> statement-breakpoint
ALTER TABLE "notes" ADD COLUMN IF NOT EXISTS "author" text;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "follow_ups" ADD CONSTRAINT "follow_ups_contact_id_contacts_id_fk" FOREIGN KEY ("contact_id") REFERENCES "public"."contacts"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "mcp_audit" ADD CONSTRAINT "mcp_audit_agent_id_mcp_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."mcp_agents"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "mcp_oauth_codes" ADD CONSTRAINT "mcp_oauth_codes_agent_id_mcp_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."mcp_agents"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "mcp_tokens" ADD CONSTRAINT "mcp_tokens_agent_id_mcp_agents_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."mcp_agents"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "follow_ups_thread_key_uq" ON "follow_ups" USING btree ("source","thread_ref","key");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "follow_ups_status_idx" ON "follow_ups" USING btree ("status");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "follow_ups_contact_idx" ON "follow_ups" USING btree ("contact_id");
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "mcp_audit_at_idx" ON "mcp_audit" USING btree ("at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "mcp_audit_agent_at_idx" ON "mcp_audit" USING btree ("agent_key","at" DESC NULLS LAST);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "mcp_tokens_agent_idx" ON "mcp_tokens" USING btree ("agent_id");
--> statement-breakpoint
DO $$ BEGIN
  ALTER TABLE "drafts" ADD CONSTRAINT "drafts_follow_up_id_follow_ups_id_fk" FOREIGN KEY ("follow_up_id") REFERENCES "public"."follow_ups"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "drafts_follow_up_id_idx" ON "drafts" USING btree ("follow_up_id");
